/**
 * ============================================================================
 * CONFIG LOADER - Dynamic Configuration from config.json
 * ============================================================================
 *
 * PURPOSE:
 * Loads tier configuration from config.json at runtime instead of hardcoding.
 * This allows the GitHub Action to inject custom tiers + Stripe price IDs
 * without modifying the Worker code.
 *
 * HOW IT WORKS:
 * 1. GitHub Action generates config.json with tiers from KV
 * 2. GitHub Action creates Stripe products (gets price IDs)
 * 3. GitHub Action writes config.json to api/src/config/config.json
 * 4. This file loads config.json and transforms it to Worker format
 * 5. All API endpoints use these tiers instead of hardcoded TIER_CONFIG
 *
 * CONFIG STRUCTURE (from GitHub Action):
 * {
 *   tiers: [
 *     {
 *       id: "free",
 *       name: "Free",
 *       price: 0,
 *       limit: 7,
 *       features: ["Basic access"],
 *       popular: false,
 *       stripePriceId: null
 *     },
 *     {
 *       id: "pro",
 *       name: "Pro",
 *       price: 29,
 *       limit: 100,
 *       features: ["Everything", "Priority support"],
 *       popular: true,
 *       stripePriceId: "price_1234abcd"
 *     }
 *   ]
 * }
 *
 * ============================================================================
 */

import { TierConfig } from '../types';

/**
 * Tier configuration from config.json (generated by GitHub Action)
 */
interface ConfigTier {
  id: string;
  name: string;
  price: number;
  limit: number | 'unlimited';
  features: string[];
  popular: boolean;
  stripePriceId: string | null;
}

interface Config {
  tiers: ConfigTier[];
  branding?: any;
  product?: any;
  apiUrl?: string;
  clerkPublishableKey?: string;
}

/**
 * MULTI-TENANT CONFIG LOADER
 *
 * TWO MODES:
 * 1. PREVIEW MODE (multi-tenant): Reads from user's KV namespace based on userId
 * 2. PRODUCTION MODE (static): Reads from bundled config.ts file
 *
 * @param env - Worker environment (for KV access)
 * @param userId - User ID from Clerk JWT (for preview mode)
 * @returns {Promise<Config>} Configuration object
 */
async function loadConfig(env?: any, userId?: string): Promise<Config> {
  try {
    // MULTI-TENANT MODE: Read from TOKENS_KV (for api-prev)
    if (userId && env?.TOKENS_KV) {
      console.log(`[ConfigLoader] MULTI-TENANT: Loading config for user ${userId}`);

      // Read tier config directly from TOKENS_KV
      const tierConfigJson = await env.TOKENS_KV.get(`user:${userId}:tierConfig`);
      if (!tierConfigJson) {
        throw new Error(`No tier config found for user: ${userId}`);
      }

      const tierData = JSON.parse(tierConfigJson) as { productName?: string; tiers: ConfigTier[] };
      console.log('[ConfigLoader] Loaded tiers from TOKENS_KV:', tierData);
      return { tiers: tierData.tiers || [] };
    }

    // STATIC MODE: Read from bundled config.ts (for customer production deploys)
    console.log('[ConfigLoader] STATIC: Loading from config.ts');
    const configModule = await import('./config');
    return configModule.config;
  } catch (error) {
    console.error('[ConfigLoader] Config load failed:', error);
    throw new Error(`Config load failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

/**
 * Transform config tiers to TIER_CONFIG format
 *
 * Converts config.json format to the TierConfig format used by the Worker.
 *
 * @param {ConfigTier[]} tiers - Tiers from config.json
 * @returns {Record<string, TierConfig>} Tier configuration map
 */
function transformTiers(tiers: ConfigTier[]): Record<string, TierConfig> {
  const tierConfig: Record<string, TierConfig> = {};

  for (const tier of tiers) {
    tierConfig[tier.id] = {
      name: tier.name,
      price: tier.price,
      limit: tier.limit === 'unlimited' ? Infinity : tier.limit,
    };
  }

  return tierConfig;
}

/**
 * Get tier configuration (multi-tenant)
 */
export async function getTierConfig(env: any, userId?: string): Promise<Record<string, TierConfig>> {
  const config = await loadConfig(env, userId);
  return transformTiers(config.tiers);
}

/**
 * Get Stripe Price ID map (multi-tenant)
 */
export async function getPriceIdMap(env: any, userId?: string): Promise<Record<string, string>> {
  const config = await loadConfig(env, userId);
  const priceIdMap: Record<string, string> = {};

  for (const tier of config.tiers) {
    if (tier.stripePriceId) {
      priceIdMap[tier.name || tier.id] = tier.stripePriceId;
    }
  }

  return priceIdMap;
}

/**
 * Get all tiers (multi-tenant)
 */
export async function getAllTiers(env: any, userId?: string): Promise<ConfigTier[]> {
  const config = await loadConfig(env, userId);
  return config.tiers;
}

/**
 * USAGE EXAMPLES:
 *
 * // Replace old TIER_CONFIG usage:
 * import { getTierConfig } from './config/configLoader';
 * const TIER_CONFIG = await getTierConfig();
 * const userLimit = TIER_CONFIG[plan].limit;
 *
 * // Replace old PRICE_ID_MAP usage:
 * import { getPriceIdMap } from './config/configLoader';
 * const priceIdMap = await getPriceIdMap(env);
 * const stripePriceId = priceIdMap[tier];
 *
 * // Get all tiers for /api/tiers endpoint:
 * import { getAllTiers } from './config/configLoader';
 * const tiers = await getAllTiers();
 * return Response.json({ tiers });
 */
